### ISSUE TITLE
Build issue on OS X (and maybe Linux)

### ISSUE THREAD

**Issue by edyu** [agocorona/haste-perch#10]
This is from "cabal install haste-perch"

Resolving dependencies...
Configuring haste-perch-0.1.0.7...
Building haste-perch-0.1.0.7...
Failed to install haste-perch-0.1.0.7
Build log ( /Users/ed/.cabal/logs/haste-perch-0.1.0.7.log ):
Configuring haste-perch-0.1.0.7...
Building haste-perch-0.1.0.7...
Preprocessing library haste-perch-0.1.0.7...
[1 of 2] Compiling Haste.App.Perch  ( Haste/App/Perch.hs, dist/build/Haste/App/Perch.o )

Haste/App/Perch.hs:42:10: Warning:
    No explicit implementation for
      ‘fmap’
    In the instance declaration for ‘Functor PerchM’

Haste/App/Perch.hs:43:10: Warning:
    No explicit implementation for
      ‘pure’ and ‘<*>’
    In the instance declaration for ‘Applicative PerchM’
[2 of 2] Compiling Haste.Perch      ( Haste/Perch.hs, dist/build/Haste/Perch.o )

Haste/Perch.hs:117:1:
    Unacceptable argument type in foreign declaration: JSString
    When checking declaration:
      foreign import ccall safe "static jsSetCB" jsSetCB
        :: Elem -> JSString -> JSFun a -> IO Bool
cabal: Error: some packages failed to install:
haste-perch-0.1.0.7 failed during the building phase. The exception was:
ExitFailure 1

**Comment by agocorona** [comment]
Ed,
It should be installed with the command

     haste-inst install haste-perch

But installing with cabal should not fail...

**Comment by edyu** [comment]
Ok, I'll do the haste-inst then.

thanks
