### ISSUE TITLE
Failed to build master

### ISSUE THREAD

**Issue by NCrashed** [agocorona/haste-perch#12]
hastec: 0.5.0
```
Haste/App/Perch.hs:280:81:
    lexical error in string/character literal at character 'p'
```

**Comment by NCrashed** [comment]
The error is fixed. But there are specific ones that appears only at 0.5.0 version:

```
Haste/App/Perch.hs:61:15: Not in scope: ‘newTextElem’

Haste/App/Perch.hs:71:9: Not in scope: ‘setAttr’

Haste/App/Perch.hs:76:15:
    Not in scope: ‘newElem’
    Perhaps you meant one of these:
      ‘nelem’ (line 75), ‘notElem’ (imported from Prelude)

Haste/App/Perch.hs:94:17: Not in scope: ‘setProp’

Haste/App/Perch.hs:97:13:
    Not in scope: type constructor or class ‘ClientCallback’

Haste/App/Perch.hs:97:42:
    Not in scope: type constructor or class ‘Event’

Haste/App/Perch.hs:100:15: Not in scope: ‘evtName’

Haste/App/Perch.hs:101:13: Not in scope: ‘getAttr’

Haste/App/Perch.hs:105:9: Not in scope: ‘onEvent’

Haste/App/Perch.hs:106:9: Not in scope: ‘setAttr’
```

**Comment by NCrashed** [comment]
Ok, I give up ^^. The `Event` was generalized in last haste-lib version and there is a need of some core changes to adapt.

**Comment by agocorona** [comment]
Hi anton,

I have been pushing some perch additions with errors sorry. But at the same
time the last version of Haste has quite different event management. I will
adapt it soon

2015-04-09 15:25 GMT+02:00 Anton Gushcha <notifications@github.com>:

> Ok, I give up ^^. The Event was generalized in last haste-lib version and
> there is a need of some core changes to adapt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/haste-perch/issues/12#issuecomment-91230933>
> .
>



-- 
Alberto.

**Comment by worldsayshi** [comment]
One of the low hanging fruits for : 
In `Haste/App/Perch.hs`, change `import Haste.App hiding (Attribute)` to:

    import Haste.App hiding (Attribute)
    import Haste.DOM hiding (Attribute,attr)

Will see if I get to the rest.

**Comment by worldsayshi** [comment]
This should be fixed now. Do you want to verify @NCrashed ?

**Comment by NCrashed** [comment]
Thank you! It's fixed.
