### ISSUE TITLE
Can't add event listeners to leaf nodes using Perch syntax?

### ISSUE THREAD

**Issue by worldsayshi** [agocorona/haste-perch#15]
This will pass:

    div $ do
            addEvent this Click $ \_ -> alert "hello, world!"

This will fail:

    input $ do
            addEvent this Click $ \_ -> alert "hello, world!"

Not strange considering the types:

    *Main> :t input
    input :: Perch
    *Main> :t div
    div :: ToElem a => a -> Perch

I'm not sure how one should set event handlers of leaf nodes.

**Comment by worldsayshi** [comment]
The workaround is to always have a wrapping node:

    div $ do
          input ! atr "type" "text"
          addEvent this Change $ \_ -> do
            writeLog "changed"

**Comment by agocorona** [comment]
input  `addEvent`  OnClick $ ( \_ _ -> alert "hello, world!")

this works

Take into account that the first parameter is the builder of an element, it it has not been created, it creates it.  

`this` is the "hook" of the perch: 
    in the monad is a reference to the container element.
    in withElems it is the element found

But it you apply addEvent directly to the element that is being build, it attach the event to that element.

**Comment by worldsayshi** [comment]
Yes this works of course. Thanks!

**Comment by worldsayshi** [comment]
For anyone stumbling in here, with the current code base it should be like this:

    input  `addEvent\`  Click $ ( \_ -> alert "hello, world!")

**Comment by worldsayshi** [comment]
*Mostly for documentations sake:*

Chaining multiple event handlers of varying concrete event types was a bit tricky. I tried this:

```haskell
addEvents elem ((evType,f):[]) =
  addEvent elem evType f
addEvents elem ((evType,f):evs) =
  addEvents (addEvent elem evType f) evs
```

With something like this:
```haskell 
input
        ! atr "type" "text"
        `addEvents` [
          (Change, \ev -> do
              ...)
        (KeyDown, \keycode -> do
         ...)]
```

... but it gave me the following error though:

```bash
editor.hs:63:10: Warning:
    Couldn't match expected type ‘BasicEvent’
                with actual type ‘KeyEvent’
    In the expression: KeyDown
    ...
```

The list can't have multiple concrete types of course. This worked though:

```haskell
((input
        ! atr "type" "text"
        `addEvent`
          Change $ \ev -> do
          ...)
        `addEvent` KeyDown $ \keycode -> do
          ...)
```

So needing to add a set of parentheses for each handler. Perhaps it's somehow possible without...
